export const ETHEREUM_PROVIDER = 'ETHEREUM_PROVIDER';
export const COLLECTIBLES_ERC_721_CONTRACT_ABI = '';
export const COLLECTIBLES_ERC_721_BYTECODE = '';
export const COLLECTIBLES_ERC_1155_CONTRACT_ABI = '';
export const COLLECTIBLES_ERC_1155_BYTECODE = '';
